apiVersion: "apps/v1"           
kind: "DeploymentConfig"              
metadata:
  name: "chat-server"           
  labels:                     
    app: "chat-server"
spec:
  replicas: 1
   triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "chat-server"
        from:
          kind: "ImageStreamTag"
          name: "chat-server:latest"                
  selector:
    matchLabels:              
      app: "chat-server"
  template:                   
    metadata:
      labels:                 
        app: "chat-server"
    spec:                     
      containers:
      - name: "chat-server"
        image: "venkateshkumar86-cts/spring-boot-sample:0.0.1-SNAPSHOT:latest"
        imagePullPolicy: Always
        ports:
          - name: "http"
            containerPort: "8080" 
apiVersion: v1                
kind: Service                 
metadata:                     
  name: "chat-server"           
  labels:                     
    app: "chat-server"
spec:                         
  type: "NodePort"               
  selector:
    app: "chat-server"          
  ports:                      
  - name: "http"
    port: "8080"
    targetPort: "8080"
